### PR TITLE
feat(dashboard): Add graphic obs drag parameters

### PR DESCRIPTION
**Pull request by EwanLyon**
Added parameters that OBS uses for the new browser source drag and drop.
Currently the layer name is just the name of the file with the `.html` removed but we could change this to add stuff like capitalization or something else.

### CODE REVIEW

**Comment by EwanLyon** [comment]
I'm not too familiar with how the tests are done so I wasn't able to write one, which by the looks of it made codecov unhappy :(

**Comment by Hoishin** [comment]
Tests are written in here: https://github.com/nodecg/nodecg/blob/master/test/dashboard.js

It uses [Puppeteer](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md) and in this case it would be something like this:

1. Find the `a` element that's made draggable for OBS
1. Figure out coordinates of the element (I haven't done this, but probably using [`elementHandle.boundingBox()`](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#elementhandleboundingbox)
1. Use the [mouse API](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#class-mouse) to mousedown, move mouse, mouseup somewhere on the page
1. After [waiting for loading new page](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions), confirm that the page's URL has desired parameters

**Comment by Dan-Shields** [comment]
I've written a test for this, but it seems like the behaviour of dropping a link somewhere on a page redirects it to that URL has been removed in recent browser releases? It doesn't work in my installations of Chrome or Firefox, and I tried it in puppeteer just in case but no redirect happened.

I can't see another way to get the URL data out of the drag event outside of creating a drop-zone dynamically inside the test.

Any ideas if there's a better way of doing it?

**Comment by Hoishin** [comment]
I think chrome opens new tab when you drop a link on a page, and puppeteer is able to find the new tab and evaluate the URL. This way should also work though.

**Review by Hoishin — APPROVED** [review]

**Comment by Dan-Shields** [comment]
Unfortunately (for us) not since this update in chrome https://chromium.googlesource.com/chromium/src/+/8bee82851b8e9bc7ab7f049194ad259743db2c97

**Comment by Hoishin** [comment]
> Unconsumed file or URL drops into Blink should navigate in a new tab

doesn't this mean if you drop a link into page it opens a new tab? (this is also the behavior on my chrome)
if so, puppeteer should be able to read the new tab's URL after dropping page

**Comment by Dan-Shields** [comment]
I'm on chrome 85 and dragging a link from one page to another opens a new tab, but when just dragging a link from one part of the page to another part of the same page nothing happens.

**Comment by Hoishin** [comment]
Ah true. I guess the only way is dropping on the tab panel that will navigate to the link

**Comment by Dan-Shields** [comment]
Yeah and unfortunately puppeteer only gives you access to what blink renders, which doesn't include any browser controls such as the tabs.

**Pull request merged**
