### PR TITLE
feat(extension): add router helper

### PR DESCRIPTION
**Pull request by Seldszar**
Small addition to the extension API which exposes the `express.Router()` method.

### CODE REVIEW

**Comment by Lange** [comment]
Nice, this makes way more sense as an API than the `.mount` method does lol

**Comment by Lange** [comment]
The tests seem to be hanging, not sure what the problem is.

**Comment by Seldszar** [comment]
Strange indeed. And for some reasons, there's warnings with the Travis's configuration file.

**Comment by Lange** [comment]
The warnings seem harmless and unrelated

**Comment by Seldszar** [comment]
I thought so, but as far I can tell, there wasn't any warnings at all before. That's why I found it strange.

**Comment by Lange** [comment]
Alright well I think NodeCG's tests have somehow rotted and don't work anymore lol. I can't get them to work locally at all. I can see no reason why this PR would introduce new failures, so I'm just gonna merge it.

**Comment by Lange** [comment]
Okay nvm, this PR does actually break all the tests. `master` still works. I'm confused

**Comment by Seldszar** [comment]
Dafuq? Tests passed on my machine without any issues. What could be wrong? :|

**Comment by Lange** [comment]
Ah ok, the problem might be that this makes browserify bundle all of express into the client build of the API, which isn't good. So you'll need to edit the browserify build config to replace express with a stub or something

**Comment by Seldszar** [comment]
Oh! At least we know who's the culprit. :)

**Pull request merged**
