### PR TITLE
Change cursor to pointer when hovering over drawer options.

### PR DESCRIPTION
**Pull request by Chr12t0pher**
It was bugging me, had to fix it ;)

### CODE REVIEW

**Comment by Lange** [comment]
Nice, thanks for the PR! Little UI tweaks are appreciated.

**Comment by Lange** [comment]
Before I merge this, can you amend your commit message to follow the [Angular guidelines](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)?

**Comment by Chr12t0pher** [comment]
Fixed.

**Comment by Lange** [comment]
Thanks a bunch! Much appreciated. :heart:

**Pull request merged**
