### PR TITLE
chore(package): implement commit message linting

### PR DESCRIPTION
**Pull request by Lange**
This project follows the [Angular commit message guidelines](https://gist.github.com/stephenparish/9941e89d80e2bc58a153), to assist in organization and to enable `CHANGELOG.md` to be [automatically generated](https://github.com/conventional-changelog/conventional-changelog) for each release.

This PR implements a git [`commit-msg`](https://git-scm.com/docs/githooks#_commit_msg) hook, which will prevent commits from being created which do not follow these guidelines.

See https://github.com/marionebl/commitlint for more details.

### CODE REVIEW

**Comment by Lange** [comment]
I may edit the commitlint config to include these 2 other categories:
- `wip`, which I use when working on a PR that I know I will squash before merging
- `tweak`, which I use for changes which aren't really features, but also aren't bug fixes. An example of this would be changing the font size of a button.

**Comment by Hoishin** [comment]
Sounds good. Been not used to forcing myself to use the style so it definitely helps.

Also a minor thing but this part could be changed https://github.com/nodecg/nodecg/blob/master/README.md#contribute

**Comment by Hoishin** [comment]
One thing I'd like to note is that we use 'Squash and Merge' feature of GitHub. So it might be too much to force every commit to follow commit message guide. The maintainers have to be careful of the merge commit message anyways.

**Comment by Lange** [comment]
You know, the more I think about it, the more you're right. Having this doesn't really help, because it does nothing to check the validity of the messages we type in `squash and merge`.

**Pull request closed without merging**
