### PR TITLE
fix(replicants): fix assignment sometimes being applied out-of-order

### LINKED ISSUE #489: Replicant assignments and operations can be emitted to clients out-of-order
Consider the following extension code:

```js
const myArrayReplicant = nodecg.Replicant('my_array');
myArrayReplicant.value.push('foo');
myArrayReplicant.value = ['bar'];
```

After this code executes, the extension will have a value of `['bar']` for this Replicant.

However, although the assignment happened after the push, browser clients will get the assignment _before_ the push, meaning that browser clients will end up with a value of `['bar', 'foo']`.

Refreshing the affected browser pages will result in them getting updated to the correct value, because they re-request it from the server, which was indeed correct this whole time. That means that this bug is one which causes divergence between the server and clients, which is pretty bad.

-----

The root problem is that assignment is always emitted immediately, whereas mutation operations are delayed until at least the next tick. The fix here is to ensure assignment gets queued in the same manner as mutation operations.

### PR DESCRIPTION
**Pull request by Lange**
Fixes #489

I chose to fix this problem by no longer treating `assignment` separately from `operations`. Now, assignment is simply a type of operation called `overwrite`. This not only fixes this bug by ensuring that assignment uses the same queue as all other operations, but it simplifies the mental model of the code by making all actions that can be taken against a Replicant be an `operation`, instead of some being `operations` and some being `assignment`, each of which had different behavior and semantics.

BREAKING CHANGE: The order in which clients receive Replicant operations has changed. It is now more deterministic and correct, but it's possible that there is code in the wild which relied on the old, buggy behavior. Also, this means a new operation type has been added, so any Replicant `change` handlers which use the third `operations` argument may need to be updated to account for both the changed order of operations, and the existence of a new `overwrite` operation.

### CODE REVIEW

**Comment by Lange** [comment]
The new test was added here: https://github.com/nodecg/nodecg/commit/67ce822c9967249b17c47b26c5cd5d214b2513ee

and I confirmed that this test fails on `master`, and passes on this branch.

**Comment by Lange** [comment]
Also: note that I'm merging this to a new branch called `2.0-dev`. I have a few breaking changes planned, so I want to batch them together into a single Major release.

**Comment by Lange** [comment]
I tested this pretty thoroughly with `sgdq19-layouts` just now, and could not find any bugs.

**Comment by Hoishin** [comment]
Sorry for keeping this PR waiting, will review sometime until the next weekend.

**Pull request merged**
