### PR TITLE
fix(replicants): Fixed an error during the proxification.

### PR DESCRIPTION
**Pull request by Seldszar**
With this additional check, only plain objects should be handled by the proxyfication process. (#369)

### CODE REVIEW

**Comment by Hoishin** [comment]
`is-plain-object` rules out arrays, and I think arrays are supposed to be handled.

**Comment by Seldszar** [comment]
You're right, my bad. I'll fix this case right now.

**Comment by Lange** [comment]
Oh, also, this PR would introduce bugs, because it would cause some properties set on a Replicant to not be captured and propagated.

For example:
```
const myRep = nodecg.Replicant('my-replicant');
myRep.value = {
    foo: new Date();
}
foo.bar = 'bar'; // The Replicant system won't see this change!
```

**Comment by Seldszar** [comment]
I see what you mean. It's not simply a bugfix, but a feature.
In this case, why not define a custom handler for `Date` types (and others)? Maybe a serializer would be needed too, especially if you want to allow custom properties.

Besides, I think I found another workaround for the error caused by the proxifycation process.
The error seems caused by a wrong context, which `Date` (and maybe other types) doesn't seems to like it. So, we just need to bind the context before returning the value.

```javascript
const CHILD_OBJECT_HANDLER = {
  get(target, prop) {
    const value = target[prop];

    if (value instanceof Function) {
      return value.bind(target);
    }

    return value;
  },

  // ...
```

I tried in the case where the replicant value is a `Date` and when a property contains one and it's working, I'll write the unit tests on my next commit, but I'll wait for a bit for having your thoughts about this solution.

**Comment by Lange** [comment]
> The error seems caused by a wrong context, which Date (and maybe other types) doesn't seems to like it. 

Interesting! If the solution is just binding the context, then that sounds like what we should do here. It's the smallest change for the most benefit.

**Comment by Seldszar** [comment]
That's more tedious unfortunately, we must find a way to only bind functions but for some reasons, objects are took in the process and cause errors during unit tests:

```
  C:\Users\Seldszar\Desktop\@nodecg\nodecg\test\schemas\server.js:13

   12:   const rep = e.apis.extension.Replicant('schema1');
   13:   t.deepEqual(rep.value, {
   14:     string: '',

  Difference:

  - bound Object {
  -   object: bound Object { … },
  -   string: '',
  - }
  + {
  +   object: Object { … },
  +   string: '',
  + }
```

```javascript
get(target, prop) {
  const value = target[prop];

  const tag = Object.prototype.toString.call(value);
  const shouldBindProperty = (
    tag === '[object Function]' ||
    tag === '[object AsyncFunction]' ||
    tag === '[object GeneratorFunction]'
  );

  if (shouldBindProperty) {
    return value.bind(target);
  }

  return value;
},
```

**Comment by Seldszar** [comment]
So, I finally managed to find the origin of the previous issue with these bound objects. It's caused by the `constructor` which is bound, because it's (obviously) a function as well.
So the solution is to simply exclude this function.

The code should look like that now:

```javascript
get(target, prop) {
  const value = target[prop];

  const tag = Object.prototype.toString.call(value);
  const shouldBindProperty = (prop !== 'constructor') && (
    tag === '[object Function]' ||
    tag === '[object AsyncFunction]' ||
    tag === '[object GeneratorFunction]'
  );

  if (shouldBindProperty) {
    return value.bind(target);
  }

  return value;
},
```

If everything is good, I'll update the pull request. I'll also add a unit test for date support.

**Comment by Lange** [comment]
Neat! Yeah go ahead and update the PR/add tests.

**Comment by Seldszar** [comment]
So, for now, we just need to fix the context issue, right?
Because it's not possible to actually keep the type between server and client and between executions (JSON stringification), data must be serialized by using something different, like BSON for example. Or maybe by writing a custom serializer which handle custom types (Date, Map, Set, etc) could be another solution.

**Comment by Lange** [comment]
Just serializing it via normal `JSON.stringify` is fine, I don't expect the entire class to be re-hydrated on the other side of the wire. The current behavior is for things to obey the normal rules of stringification, and Dates should be no exception here for the time being. The fix is just making it so that Dates don't cause these unhandled errors.

**Comment by Seldszar** [comment]
Got it! I just wanted to be sure about that.

**Comment by Lange** [comment]
LGTM! 👍

Is this ready to merge, @Seldszar?

**Comment by Seldszar** [comment]
Yup, ready to launch!

**Pull request merged**
