### PR TITLE
test: Updated unit tests to take account the new behavior.

### LINKED ISSUE #378: Test stops in the middle
screen shot 2018-02-14 at 20 19 52

The test stucks at the job added in https://github.com/nodecg/nodecg/commit/4d42335947fc820895b3a888a31a1fbfbf4989f1 and eventually fails. I'd guess it reload and fail again and again?

### PR DESCRIPTION
**Pull request by Seldszar**
Closes #378.

### CODE REVIEW

**Comment by Lange** [comment]
Looks like this hung on travis, I'm not sure why.

**Comment by Lange** [comment]
I restarted the build, we'll see if it happens again.

**Comment by Lange** [comment]
Looks like it hung at the same point.

**Comment by Seldszar** [comment]
Yeah, but I don't know where exactly. Locally, it's stuck somewhere else, but passes the bundle tests. I'll check this again.

OK, I'm really dumb, I forgot to actually add the line to make the manifest invalid, sorry about that.

There we go, perfect!

**Pull request merged**
