### PR TITLE
 feat(extension): add Babel/TypeScript `export default` support and conditional calling

### PR DESCRIPTION
**Pull request by Seldszar**
The pull request adds two features:

- ECMAScript module support, useful when using a bundler and removes the need of including compatibility plugins/code
- Conditional function calling, which can be handy when the module is an utility bundle for example

### CODE REVIEW

**Comment by Hoishin** [comment]
1. Can you `require` ES modules? https://nodejs.org/api/esm.html#esm_unsupported
2. Now that you mentioned it, it's probably better to throw a useful error if it find extension that is not a function.

**Comment by Seldszar** [comment]
1. Didn't test with these and it's too soon for adding this kind of compatibility. I was talking about bundlers which are using Babel for emulating the ESM behavior by exporting as `default` and adding a `__esModule` property.
2. I'd prefer giving developers more possibilities because, in the end, the extension will contain the result returned by the initiator which can be anything. But if you say so.

**Comment by Hoishin** [comment]
Thank you for clarification.

For 2, it would be great to have reasonable use cases to have extra lines of code and extra logics. I cannot think of any.
@Lange uses NodeCG more than me (obviously) so I wonder if he has anything in his mind.

I'll update the title to reflect first point.

**Comment by Lange** [comment]
Yeah if there's an actual use case for loading an extension which doesn't export a function, I'd be happy to review that use case. However, as it stands, I don't see it being a common use case, because an extension which doesn't export a function would have no way to access the NodeCG API.

**Comment by Lange** [comment]
I'm going to close this for now, because it is already pretty easy to get extensions written in TypeScript to load without having to make this kind of change to NodeCG core. I also don't want to make this change to NodeCG core yet, because ES Module support is still not finalized in Node.js ([their status is "Experimental" as of right now](https://nodejs.org/api/esm.html)).

Once ES Modules are finalized in Node, I think it will make sense to re-evaluate this and implement an idiomatic solution.

**Pull request closed without merging**
