### PR TITLE
feat(replicants): add default value factory

### LINKED ISSUE #486: Getting defaultValue of a replicant returns current value for some data types
If you try to get the default value (`replicant.opts.defaultValue`) of certain replicants, for example if it an object, it will return the same as the current replicant instead. The default value needs some cloning when it's initialised.

### PR DESCRIPTION
**Pull request by Seldszar**
This change adds the ability to use factory functions for creating default values, avoiding issues where default values are passed by reference, like objects, being mutated.

```js
const replicant = nodecgReplicant("defaultFactory", {
  defaultValue: () => ({ lorem: "ipsum" })
});
```

### CODE REVIEW

**Review by Hoishin — CHANGES_REQUESTED** [review]
This approach does not solve the issue because if you return an object reference in the factory, it will fall into the same problem.

**Comment by zoton2** [comment]
This doesn't help if the defaultValue is derived from a schema does it?

**Comment by Seldszar** [comment]
> This approach does not solve the issue because if you return an object reference in the factory, it will fall into the same problem.

Didn't think about this possibility, cloning remains the best option it seems.

**Comment by Seldszar** [comment]
I think I'll close this PR and open a new one using the cloning approach.

> This doesn't help if the defaultValue is derived from a schema does it?

The result will still be the same I think, the value will still be a reference to the default one. I didn't understand the issue until recently and the factory will be useless, especially with a schema.

**Pull request closed without merging**
