### PR TITLE
Updates to documentation

### PR DESCRIPTION
**Pull request by atribecalledkwest**
Resubmitting this pull request from a while ago. Contains a few modifications from the original PR, but is mostly the same.

### CODE REVIEW

**Comment by Lange** [comment]
Hm, looks like I have more bugs to fix with coverage stats.

**Comment by Lange** [comment]
I've made my edits. Additional review and suggestions from folks are welcome. My goal is to merge this PR by end-of-day.

**Comment by Dan-Shields** [comment]
If #410 gets merged the section reading `There is a limitation to this, however; a Message cannot be sent from server extension to server extension. In these cases, you will want to look into NodeJS's built in EventEmitters.` should be removed from the concepts and terminology page.

Not sure if this should be changed here or in #410.

**Comment by Lange** [comment]
@Dan-Shields Good catch, easiest to change it here.

**Comment by Lange** [comment]
Another great catch @Dan-Shields, thanks! I've pushed a fix to this branch.

**Pull request merged**
