### PR TITLE
chore(package): update chokidar

### PR DESCRIPTION
**Pull request by Lange**
To the best of my knowledge, chokidar is the only prodDep we have which still triggers an `npm audit` warning. This is because of a deeply nested dependency on a vulnerable version of `braces`.

### CODE REVIEW

**Comment by Hoishin** [comment]
@Lange chokidar's v2 breaking change was concerning for me when I was doing the chores. Do you know if it affects us or not?
https://github.com/paulmillr/chokidar/blob/master/CHANGELOG.md#chokidar-200-dec-29-2017

**Comment by Lange** [comment]
@Hoishin It seems to be okay. I looked through our usages of `chokidar`, and I don't think we use Windows-style path separators anywhere. I also fired this up on my local Windows machine, and it seems okay.

**Comment by Lange** [comment]
Actually, seeing one test failure on Windows. Working on it.

**Comment by Lange** [comment]
Yeah, turns out that we have to re-write any place we use `path` to build a path: https://github.com/paulmillr/chokidar/issues/777

**Comment by Lange** [comment]
Should be fixed now. This also makes it apparent that we need to run CI on all 3 platforms (Linux, macOS, Windows). We should do this by migrating to Azure Pipelines after #415 is merged.

**Comment by Lange** [comment]
Okay, all tests passing on Windows now.

**Pull request merged**
