### PR TITLE
feat(api): add nodecg.bundleGit object

### PR DESCRIPTION
**Pull request by Lange**
Useful for error reporting, diagnostics, postmortems, etc.

May also be used in some upcoming NodeCG core features.

`bundleGit` object looks like this:
```js
{
	branch: 'master',
	date: new Date('2018-07-13T17:09:29.000Z'),
	hash: '6262681c7f35eccd7293d57a50bdd25e4cd90684',
	message: 'Initial commit',
	shortHash: '6262681'
}
```

### CODE REVIEW

**Comment by haganbmj** [comment]
So these are manually written right? The plan isn't to query for the details based on a hash or something.

**Comment by Lange** [comment]
Can you elaborate? I'm not understanding the question

**Comment by haganbmj** [comment]
Nevermind, I'm terrible with words.
Read a bit further and now I see where you're extracting these details from the `.git` directory in the bundle.

**Comment by Lange** [comment]
Ah kk, yeah all the magic is handled here: https://github.com/nodecg/nodecg/blob/master/lib/bundle-parser/git.js

**Pull request merged**
