### PR TITLE
 Add basic local authentication

### PR DESCRIPTION
**Pull request by erynnb**
Added the [passport-local](https://github.com/jaredhanson/passport-local) strategy so users can use a username and password instead of Steam or Twitch. You are able to specify multiple users in the ./cfg/nodecg.json file that are able to login using local authentication. 

	"login": {
		"enabled": true,
		"sessionSecret": "supersecret",
		"local": {
			"enabled": true,
			"allowedUsers": [
				{
					"username": "admin",
					"password": "password"
				},
				{
					"username": "erynn",
					"password": "1234"
				}
			]
		}
	}

Not sure if this is the best way to do this but I think it is probably the simplest.

### CODE REVIEW

**Comment by Lange** [comment]
This looks good! @MattMcNam is this what you had in mind in #372? Any other features you wanted?

**Comment by Hoishin** [comment]
What is the target usage of this? Do you expect just one or two users defined and used so you don’t have to care about exposing plain password?

It would be serious vulnerability if it is just defining plain password in the config file, and someone get someone else’s password.
If I remember correctly contents inside nodecg.json is exposed in front-side. (with nodecg.ncgConfig or something)

(In that matter it already exposes Twitter API keys and session secrets and stuff, but plain password is whole another level of privacy, IMO)

**Comment by Lange** [comment]
> If I remember correctly contents inside nodecg.json is exposed in front-side. (with nodecg.ncgConfig or something)

This is incorrect. NodeCG creates a "filtered" copy of `nodecg.json` with sensitive data removed: https://github.com/nodecg/nodecg/blob/master/lib/config/loader.js#L264-L282

**Comment by Hoishin** [comment]
hmm is this filtered as intended?

screen shot 2018-04-29 at 02 58 48

**Comment by Hoishin** [comment]
Yes, what I said in the latter half was wrong. 

I'm still kind of worried having password in config file, but probably fine for this kind of system (by that I mean a system that has very specific users being able to login and use).

**Comment by Lange** [comment]
The API keys and tokens are just as dangerous to have in the config file, there's no difference between them and passwords. There's not really any way for us to secure this info unless we prompt for a decryption password every time NodeCG starts up or something.

**Comment by Hoishin** [comment]
That's a good point. I can't really think of good way to implement encryption either now, unless making big changes to authentication system, which is probably not preferred.

**Comment by Lange** [comment]
If the connection is made over HTTP, then yeah. We'd have to implement a salting and hashing system to not transmit passwords over the wire to eliminate that issue.

**Comment by MattMcNam** [comment]
@erynnb @Lange LGTM! Sorry for silence on #372, dealing with a laptop that 💩 itself and lost the code & other personal stuff lately.

Regarding MITM: I'd rather push users towards using HTTPS either via paid certs, Let's Encrypt or even self-signing certs.

**Comment by TBSliver** [comment]
Hmm any possibility this could get added soon? It will be extremely useful, as not everyone who is going to be helping will have a twitch or steam login.

As for HTTPS, if people want to deploy this on an externally visible server, then thats very much their own problem - there are too many options and use cases out there to document it all, though documenting that it is recommend to deploy it behind an SSL cert is not a bad idea if deploying externally. There are also instances where anything but self-signed certs is impossible, such as running inside a LAN (which is my exact use case).

Also if you're worried about the bundle data exposing the config options, just set them to a different config file - and optionally either automatically encrypt the passwords on first read, or require the passwords to be put in encrypted (and use a cli program such as `mkpasswd` to generate well hashed  passwords).

**Comment by Lange** [comment]
Sorry for the long delay on this. It's been merged and released as v0.9.12.

**Pull request merged**
