### PR TITLE
MINOR: Update headings in README to be more consistent

### PR DESCRIPTION
**Pull request by madmatt**

### CODE REVIEW

**Comment by madmatt** [comment]
Seems to be an issue with Sauce Labs authentication (no username/access token provided to Sauce Labs), suspect that's an issue with the secure tokens or Travis configuration perhaps?

**Comment by Lange** [comment]
Thanks! And yeah, when we first set up our Sauce Labs configuration the limitation was that PRs could never have passing tests. I believe this is because PRs aren't given the ability to use encrypted environment variables on Travis, because then those secret values could be stolen.

It's possible that there is a new way of setting up Sauce Labs that works around this limitation, but I do not personally know of it.

**Comment by madmatt** [comment]
Ah I see, that makes sense but is annoying.

[Travis CI recommends running tests but disabling those that require secure variables](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions) when run on pull requests. Would you be happy if I made a PR to do that (don't run any tests that require Sauce Labs, but still run the unit tests that don't require it)? At least it would result in some base level of passing tests, although on the other hand it might give false confidence that the pull request is more solid than it actually is.

**Comment by Lange** [comment]
Sure! Having some degree of testing would be better than nothing. @MattMcNam might also find time to refactor our tests to use a local selenium rather than Sauce Labs, which would eliminate the need for these secure variables.

**Comment by MattMcNam** [comment]
Just a heads up @madmatt, I've merged a change that will run tests for pull requests now!

**Comment by madmatt** [comment]
Awesome :)

**Pull request merged**
