### PR TITLE
Feature: Docker Image Impovment

### PR DESCRIPTION
**Pull request by Nols1000**
Improve Docker support by using a non-root user to execute nodecg.(https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user)
Also changed the workdir to "/opt/nodecg" as "/opt" it's supposed to be used to install programs.
Also Adding Volumes. (https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#volume) 
Also Using yarn instead of npm, because of it's advantages. (nodejs/docker-node#243)

### CODE REVIEW

**Comment by Lange** [comment]
Thanks for this!

I'm familiar with yarn, but what specific advantages does it have over npm5? I don't personally use yarn as I'm quite happy with npm5, so I'm hesitant to add it here.

**Comment by Nols1000** [comment]
I think I added yarn because of the message by bower (bower/bower#2407) and then I didn't change it back when I learned about yarn dropped the bower support. I use them both but heard a lot about yarn being better than npm and as it is part of the node docker-image I thought using it would be better.

**Comment by Lange** [comment]
Ah I see. For now, let's stick to npm5, as I don't think that using yarn has any tangible benefits for this use case, and I'd need a pretty good reason for introducing an alternative package manager into NodeCG's workflow.

**Comment by Lange** [comment]
I'll need to try this out on some of my Docker deployments to see how things work -- I'll try to get back to you within a few days.

**Comment by Lange** [comment]
Haven't forgotten about this, just haven't had a chance to try it out yet. Sorry!

**Comment by Nols1000** [comment]
As you use another Dockerfile I wanted to point out, that this implementation uses a non root user. This is the recommended behavior although it could cause problems especially for Windows users. I think it would be the best solution to close this PR. If you have any questions you can ask me.

**Pull request closed without merging**
